Calculating the derivatives is very important, but prone to error. We can use *automatic differentiation* or *autograd* to speed up this progress using computational graphs.

In [17]:
import torch

We are interested in differentiating $y = 2\mathbf{x}^T\mathbf{x}$

In [18]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [19]:
x.requires_grad_(True)
print(x.grad)

None


In [20]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [21]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

We know that the gradient of the function $y = 2\mathbf{x}^T\mathbf{x}$ with respect to $x$ should be $4x$.

In [22]:
x.grad == 4 * x

tensor([True, True, True, True])

In [24]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad, y

(tensor([1., 1., 1., 1.]), tensor(6., grad_fn=<SumBackward0>))

In [26]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [27]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [28]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [32]:
a.grad == d / a

tensor(True)

: 