In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [5]:
x.reshape(-1, 1)

tensor([[0],
        [1],
        [2]])

In [15]:
x[2]

tensor(2)

In [16]:
len(x)

3

In [17]:
x.shape

torch.Size([3])

In [18]:
A = torch.arange(6).reshape(-1, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [21]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matrices are the subset of square matrices that are equal to their own transpose $\mathbf{A} = \mathbf{A}^T$

In [22]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A, A.T, A == A.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [23]:
torch.arange(24).reshape(-1, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

A handy property of same shape matrices is that we can use element-wise computation like the Hadamard product $A \circ B$

In [24]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [26]:
A * B # Hadamard product

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

Adding or multiplying a scalar and a tensor produces a new tensor with the same shape as the old tensor

In [28]:
a = 2
X = torch.arange(24).reshape(-1, 3, 4)
a + X, a * X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [31]:
A, A.sum(), A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.),
 torch.Size([2, 3]))

In [32]:
A.shape, A.sum(dim=0)

(torch.Size([2, 3]), tensor([3., 5., 7.]))

In [33]:
A.shape, A.sum(dim=1)

(torch.Size([2, 3]), tensor([ 3., 12.]))

In [34]:
A.sum(dim=[0,1]) == A.sum()

tensor(True)

In [35]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

Again, we can calculate something along a certain dimension

In [37]:
A.mean(dim=0), A

(tensor([1.5000, 2.5000, 3.5000]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]))