In [2]:
import torch 
from torch import nn 
from torch.nn import functional as F
from d2l import torch as d2l

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__() 

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.LazyLinear(256), CenteredLayer())

c:\Users\alexa\Documents\Uni\Personal Projects\Dive-into-Deep-Learning\dive_into_deep_learning\Lib\site-packages\torch\nn\modules\lazy.py:181: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [7]:
y = net(torch.rand(4, 8))
y.mean()

tensor(2.7940e-09, grad_fn=<MeanBackward0>)

In [15]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [17]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.1552,  0.2344,  0.3469],
        [-0.3550,  2.1988, -1.3191],
        [-0.2076,  0.4823,  0.4108],
        [-0.4922,  0.7132, -0.6925],
        [ 0.9965, -0.1025,  1.1272]], requires_grad=True)

In [18]:
linear(torch.randn(2, 5))

tensor([[0.0000, 2.5912, 0.0000],
        [0.0000, 4.4918, 0.0000]])

In [19]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.randn(2, 64))

tensor([[26.0729],
        [ 1.6885]])