In [36]:
import torch

In [37]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [38]:
x.numel()

12

In [39]:
x.shape

torch.Size([12])

In [40]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
# Using -1 for the shape component infers it automatically
# So this will do the same as before
X_1 = x.reshape(3, -1)
X_1

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
# Or this
X_2 = x.reshape(-1, 4)
X_2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [43]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [44]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [45]:
# We often want to initalize our matrices randomly and indepently from a distribution.
# This does that for a standard Gaussian (normal) distribution with mean 0 and sd 1
torch.randn(3, 4)

tensor([[-0.0640, -0.7554, -1.5627,  1.3888],
        [ 0.2492, -1.0524,  0.5212,  1.0436],
        [-0.8996, -0.7311, -0.7159, -0.6553]])

In [46]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [47]:
X[-1], X[1:3], X[:1]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[0., 1., 2., 3.]]))

In [48]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [49]:
X[:2, :2] = 12
X

tensor([[12., 12.,  2.,  3.],
        [12., 12., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [50]:
X = x.reshape(3, 4)
X

tensor([[12., 12.,  2.,  3.],
        [12., 12., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[:2, :1] = 12
X

tensor([[12., 12.,  2.,  3.],
        [12., 12., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [52]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

We can have functions that map any real number to some other real number, these are called *unary* scalar operators $f: \mathbb{R} \rightarrow \mathbb{R}$.

In [53]:
# For example
torch.exp(X)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

We also have *binary* scalar operators $f: \mathbb{R}^d, \mathbb{R}^d \rightarrow \mathbb{R}^d$

In [54]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [55]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [56]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [58]:
X.sum()

tensor(66.)

When tensors don't match up, we can utilize broadcasting like the following example

In [59]:
a = torch.arange(3).reshape((-1, 1))
b = torch.arange(2).reshape((1, -1))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [60]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Memory gets allocated to different areas, this might be unfortunate

In [64]:
before = id(Y)
Y = Y + X
after = id(Y)
before == after

False

This is undesirable, but luckily we can do computations **in-place**.

In [67]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1877796885168
id(Z): 1877796885168


In [68]:
before = id(X)
X += Y
id(X) == before

True

In [70]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [72]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [76]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [83]:
p = torch.arange(27).reshape((-1, 3, 3))
q = torch.arange(3).reshape(1, -1)
q, p, q + p

(tensor([[0, 1, 2]]),
 tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],
 
         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]]),
 tensor([[[ 0,  2,  4],
          [ 3,  5,  7],
          [ 6,  8, 10]],
 
         [[ 9, 11, 13],
          [12, 14, 16],
          [15, 17, 19]],
 
         [[18, 20, 22],
          [21, 23, 25],
          [24, 26, 28]]]))